# Generated by Django 5.0.6 on 2024-06-24 10:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '활성화'), ('inactive', '비활성화')], default='active', max_length=10)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_groups', to=settings.AUTH_USER_MODEL)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('super_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='home.group'),
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_group', models.CharField(max_length=255)),
                ('original_link', models.URLField(max_length=1024)),
                ('shortened_link', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 24, 10, 55, 56, 891456, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('accessible', '접속 가능'), ('inaccessible', '접속 불가능'), ('group_modified', '그룹 관리자 수정'), ('owner_modified', '소유자 수정')], default='accessible', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
