# Generated by Django 5.0.6 on 2024-06-25 03:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_group_group_name_alter_url_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='super_admin',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 3, 47, 42, 666137, tzinfo=datetime.timezone.utc)),
        ),
    ]
