# Generated by Django 5.0.6 on 2024-06-25 03:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_group_super_admin_alter_url_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='group',
            name='super_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 3, 50, 11, 336407, tzinfo=datetime.timezone.utc)),
        ),
    ]
